### PR TITLE
Expose broker URLs in loadbalancer registration node

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

To allow for Service discovery module to redirect between https and http, it needs to have
access to all broker addresses.

### Modifications

When broker register itself, it will provide the URLs in the load-balancer registration node.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by sboobna** [comment]
👍

**Pull request merged**
