### PR TITLE
Added DbLedgerStorage configuration keys with default values in bookkeeper.conf

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Added missing configuration keys for BookKeeper DbLedgerStorage

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by sschepens** [comment]
@merlimat do you have any recommendations for rocksdb tuning? I believe if we set `writeCacheMaxSizeMb` very high, a single flush would write a lot of level0 files, which would probably be above `rocksDB_numFilesInLevel0` and it will begin to [stall writes](https://github.com/facebook/rocksdb/wiki/Write-Stalls). Am I correct?

Is there a good ratio between `writeCacheMaxSizeMb` and `rocksDB_writeBufferSizeMB` you find useful?

**Comment by sschepens** [comment]
@merlimat please read my recent comments on #110

**Comment by merlimat** [comment]
@sschepens  In DbLedgerStorage, RocksDB is used to just store the indexes, not the actual entries payloads. All writes to RocksDB are done in a background flush thread, so the stall are not a concern here.

To recap: 
 * `dbStorage_writeCacheMaxSizeMb` : Memory portion where payloads are accumulated before flushing. Ideally this should big enough to accumulate ~1min worth of entries
 * `dbStorage_rocksDB_writeBufferSizeMB` : Size of RocksDB memtable. I don't think this need to be increased from the default 64MB
 * `dbStorage_rocksDB_blockCacheSize` : This is the RocksDB cache, used when reading. It should be big enough to hold the "active" portion of database to avoid disk access to read the indexes.

**Pull request merged**
