### PR TITLE
Added log4j with info logs for pulsar-broker unit tests

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Add default log4j config for pulsar-broker unit tests

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by merlimat** [comment]
Apparently, Travis has a limit of 4MB for job output and with this change that would be exceeded. I'll add the log4j conf file with default to off for now.

**Pull request merged**
