### PR TITLE
Replace messagesToReplay set to ConcurrentLongPairSet to improve gc

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

As part of #398 : In usecase when shared-subscription has large number of unack messages, redelivery makes `PersistentDispatcherMultipleConsumers` to store large number of `PositionImpl` into `messagesToReplay` set which can be a one of the factor for frequent gc at broker. So, storing message-positions into primitive set can help to improve gc.
Note: rebased on #405 

### Modifications

Change `messagesToReplay` type to `ConcurrentLongPairSet`

### Result

No functional change.

### CODE REVIEW

**Comment by saandrews** [comment]
Though using this will resolve broker side of issue, I am not sure if clients would prefer to see older messages deliver much later which could happen if we don't maintain order with unacked list. Some use cases have many tens of consumers, so 200k unacked could cause some older message linger for a long time before delivered.

**Comment by merlimat** [comment]
@saandrews Though the out-of-order acks are now being persisted. So you'll get the 200K messages, in no particular order, but without the risk of getting everything back again.

**Comment by rdhabalia** [comment]
I think what @saandrews  is mentioning that right now, with ordering there is a predictability that out of 200K msgs in messageReplay-bucket, broker always dispatch oldest unacked-messages and client is getting opportunity to receive and process oldest unack-messages. However, I am not sure sending oldest unack-msgs and keeping predictability of ordering message-redelivery will be useful for client or not.
I am going to do another round of test similar we did for #399 and will post the result with this patch.

**Comment by merlimat** [comment]
@rdhabalia @saandrews 
The other option would be to have a priority queue (min-heap), of (long, long) to get the positions out in order.

**Comment by rdhabalia** [comment]
> The other option would be to have a priority queue (min-heap), of (long, long) to get the positions out in order.

yes, I think that could be a right option. though do you think if this queue is already available as part of library else we can create one.
I will try to collect test-result and if looks fine then will merge the PR.

**Comment by merlimat** [comment]
> yes, I think that could be a right option. though do you think if this queue is already available as part of library else we can create one.

We would have to create one specialized for (long,long) values. Thread safety shouldn't be an issue given that it's already behind a mutex.

Though, using the priority queue has a different impact than hash-map (logN for both insert and remove) and also we cannot just peen N items and later remove, so the logic in the dispatcher would need to change a bit.

**Comment by rdhabalia** [comment]
After adding this change:
young gc: avg 300 msec

screenshot from without-changes

**Comment by merlimat** [comment]
@rdhabalia Looks good. Though try to get the x-axis aggregation to 1min, otherwise you might see the y-values averaged out over the 1hour period.

**Comment by rdhabalia** [comment]
1. Without any change: frequent young-gc and old-gc
screenshot from without-changes

2. with dispatcher block changes: no old gc but avg young-gc 2 sec
screenshot from without-changes

3. with (2) and primitive collections at consumer and dispatcher: young-gc : 850 msec
screenshot from without-changes

Please click on image to see clear number.

**Comment by merlimat** [comment]
Thanks @rdhabalia. I think we can go ahead and merge this PR, unless you guys want to look at the priority queue approach. 
I'd vote for merging this now.

Also, the ~600ms is still quite high (though not as tragic as before ;) ) and we should try to understand a bit more on what driving that.

**Comment by rdhabalia** [comment]
> Also, the ~600ms is still quite high (though not as tragic as before ;) ) and we should try to understand a bit more on what driving that.

yes, will spend some more time to take a deeper look in it.

> I think we can go ahead and merge this PR, unless you guys want to look at the priority queue approach. I'd vote for merging this now.

yes, we are thinking to support message ordering but we can merge it for now and can introduce with next PR. @saandrews any suggestion?

**Comment by saandrews** [comment]
Ok, lets merge this for now. I almost see customers complain about it when we break ordering. So, we should get that as well if the penalty isn't bad.

**Comment by merlimat** [comment]
>  I almost see customers complain about it when we break ordering 

Ordering is already _broken_ on message redeliveries 😃

**Comment by rdhabalia** [comment]
> Though, using the priority queue has a different impact than hash-map (logN for both insert and remove) and also we cannot just peen N items and later remove, so the logic in the dispatcher would need to change a bit.

I think we also need HashSet on top of (long,long) priority-queue to make sure it stores unique elements along with min-heap.  I think it will create some more complexity as well. So, probably should we keep `TreeSet` for ordering or we can trade ordering with existing `ConcurrentLongPairSet` ?

**Comment by rdhabalia** [comment]
@saandrews as we know now that it was a mistake at client side while checking logs regarding not getting messages on redelivery, so there might not be any issue if we don't follow the ordering.
So, even if `messageReplay` bucket has 200K messages, it could get delivered in 10 mins on redelivery and as it is a shared subscription, messages are not going in order to any consumer. So, anyway in shared-subscription ordering is broken.
So, I think we can merge this PR right now, and can introduce priority min queue if we see further issue.?

**Comment by saandrews** [comment]
@rdhabalia Your claim of mistake at client side is not confirmed yet.  Irrespective of that outcome, my point was not about this use case. In general we could end up with older messages in the unacked list while delivering newer messages, when the replay list is not drained.

Let us merge this for now and address it if we come across a use case.

**Pull request merged**
