### PR TITLE
increment bookkeeper version

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Upgraded bookkeeper-version with changes:
- [Upgrade rocksDb version](https://github.com/yahoo/bookkeeper/pull/5)
- [Support DbLedgerStorage in LedgerCmd to get list of logger files](https://github.com/yahoo/bookkeeper/pull/6)
- [Add Prometheus stats provider](https://github.com/yahoo/bookkeeper/pull/7)

@merlimat : If you already have PR to add additional configuration for prometheus-stats-provider then please feel free to close this PR.

### CODE REVIEW

**Comment by merlimat** [comment]
@rdhabalia While you're at it, can you also include the prometheus dependency in the `all/pom.xml`. This way it gets included in the binary distribution.

**Comment by merlimat** [comment]
@rdhabalia One more issue. The build is failing with a rocksdb java wrapper issue: 

```
Running TestSuite
/usr/lib/jvm/java-8-oracle/jre/bin/java: symbol lookup error: /tmp/librocksdbjni1935689833567743276.so: undefined symbol: ZSTD_versionNumber
```

Issue was already solved in rocksdb: 
https://github.com/facebook/rocksdb/issues/2280

**Comment by rdhabalia** [comment]
should we increment rocksDb version to `5.3.6`?

**Comment by merlimat** [comment]
https://github.com/yahoo/bookkeeper/pull/9

**Comment by rdhabalia** [comment]
will update with new bk-version once it will be done.

**Comment by rdhabalia** [comment]
@merlimat do we have anything else for 1.18, should we release it once this build passes?

**Comment by merlimat** [comment]
I think we should be good with this

**Pull request merged**
