### PR TITLE
Fixed incorrect links

### PR DESCRIPTION
**Pull request by mmonti**
### Motivation

Documentation links were broken.
Added "./" to fix the link

### Modifications

Modified links in README.md

### Result

After your change, what will change.

Fixed incorrect links for Getting Started, Architecture and Documentation Index.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by merlimat** [comment]
On the regular github interface I'm able to click on the links even without the `./` prefix, where are you seeing the links failing?

**Comment by mmonti** [comment]
Well... Is working for me now. I tried to access the documentation using the links on the readme and  it was redirecting me to the Github 404 page. 
I though was the link, thats why I added the "./",  but seems that is fine now. Ill just close it.

**Pull request closed without merging**
