### PR TITLE
Replace usages of Atomic* for Atomic*FieldUpdater

### PR DESCRIPTION
**Pull request by sschepens**
Replaced some usages of AtomicInteger, AtomicLong and AtomicReference for their Atomic*FieldUpdater counterpart on classes which get instantiated a lot, this should reduce memory usage for the broker and clients which use lots of topics and consumers.

### CODE REVIEW

**Comment by merlimat** [comment]
Change looks good, though there are few tests failing in travis build. eg: 

```
2017-02-08 17:29:48,710 - INFO  - [main:TestListener@53] - @@@@@@@@@@@@@ STARTING TEST - com.yahoo.pulsar.broker.service.ResendRequestTest / testExclusiveCumulativeAckedNormalTopic -- attrs: []
2017-02-08 17:30:19,760 - ERROR - [main:TestListener@41] - ------------ Test Failed - 
```

**Comment by sschepens** [comment]
@merlimat couldn't reproduce this errors on my machine, but I did realize that Travis is running extremely slow, maybe this is producing the failures?

**Comment by saandrews** [comment]
Do you know of any performance impact in switching to this, since it uses reflection?
For the build issue, Can you restart and see if it succeeds? Travis build env is super slow.

**Comment by sschepens** [comment]
@saandrews it shouldn't have any performance impact that I know of, in fact it should benefit performance, since it reduces memory usage, and so gc pauses.

I cannot restart the build in Travis, maybe @merlimat can

**Comment by merlimat** [comment]
> Do you know of any performance impact in switching to this, since it uses reflection?

@saandrews  The reflection is only used at static load time of the class. Using the updater is actually faster because is treated as an intrinsic operation by jvm (apart from the spared allocation).

**Comment by rdhabalia** [comment]
@sschepens 
>I cannot restart the build in Travis, maybe @merlimat can

After restarting the build: It took around 49 mins and then it has been terminated as it reached max time-limit of build-job: https://api.travis-ci.org/jobs/199668485/log.txt?deansi=true
Do you want to check it or I can trigger another time.

**Comment by sschepens** [comment]
@rdhabalia I will indeed check it

**Comment by sschepens** [comment]
@saandrews @merlimat @rdhabalia the issue seemed to be that I accidentally defaulted OwnedBundles to `isActive = false`.
Tests should run now.

**Comment by sschepens** [comment]
@merlimat @rdhabalia I'm investigating test failues.
Apparently the issue seems to be that we're creating [spies of Producer](https://github.com/sschepens/pulsar/blob/01869030c2c46e070ea8158afb6c5dbcaec9e7b4/pulsar-broker/src/test/java/com/yahoo/pulsar/client/impl/MessageIdTest.java#L331)
This creates a new instance of a class, and so when updating the [state](https://github.com/sschepens/pulsar/blob/01869030c2c46e070ea8158afb6c5dbcaec9e7b4/pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/HandlerBase.java#L29) it actually updates the internal state of the spy and not of the original producer.

Maybe we can change the test to not spy on the producer, or have all changes to state go through methods so they get proxied to the original instance.

What do you guys think?

**Comment by sschepens** [comment]
@merlimat @rdhabalia I managed to fix the failing tests making spies proxy method calls to original instances, please check the tests I modified

**Pull request merged**
